learning_templates/brainapp/urls.py
from django.urls import path
from brainapp import views


# TEMPLATE TAGGING
app_name = 'brainapp'

urlpatterns= [
path('relative',views.relative, name= 'relative'),
path('other',views.other, name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from brainapp import views


urlpatterns = [
    path('',views.index, name = 'index'),
    path('brainapp/', include('brainapp.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/brainapp/models.py
from django.db import models

# Create your models here.

learning_templates/brainapp/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
        context_dict = {'text':'hello world', 'number':100}
        return render (request,'brainapp/index.html', context_dict)


def other(request):
    return render(request,'brainapp/other.html')

def relative(request):
    return render(request,'brainapp/relative_url_template.html')

learning_templates/templates/brainapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'brainapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>


    <div class="container">
      {% block body_block %}

      {% endblock %}

    </div>

  </body>
</html>

learning_templates/templates/brainapp/index.html
<!DOCTYPE html>
{% extends "brainapp/base.html" %}
    {% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <h1>{{ text | cut:'hello' }}</h1>
    <h1>{{ number|add:'99' }}</h1>

    {% endblock %}

learning_templates/templates/brainapp/other.html
<!DOCTYPE html>
{% extends "brainapp/base.html" %}
    {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>this is an example of template inheritance!</h2>
    {% endblock %}

learning_templates/templates/brainapp/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'brainapp:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">admin</a>
    <a href="{% url 'index' %}">link to index</a>

  </body>
</html>